INSERT INTO burgers (name) VALUES ('Double Dipper');
INSERT INTO burgers (name) VALUES ('Dude Ranch');
INSERT INTO burgers (name, devoured) VALUES ('Rustler', true);
INSERT INTO burgers (name, devoured) VALUES ('Veggie Rustler', true);
INSERT INTO burgers (name, devoured) VALUES ('Avocado Sagebrush', true);
INSERT INTO burgers (name) VALUES ('Plain Wayne');
INSERT INTO burgers (name) VALUES ('Hotty Habanero');
INSERT INTO burgers (name) VALUES ('Bunless Wonder');
INSERT INTO burgers (name) VALUES ('Cheddar Smokestack');
INSERT INTO burgers (name) VALUES ('Little Tofu Sprout');
